pipeline {

agent any

environment {

    DATABRICKS_HOST = credentials('DATABRICKS_HOST')
    DATABRICKS_TOKEN = credentials('DATABRICKS_TOKEN')

    JOB_ID = "123456789"

    IMAGE_NAME = "engineering-ai"

    IMAGE_TAG = "${BUILD_NUMBER}"
}

options {
    timestamps()
    buildDiscarder(logRotator(numToKeepStr: '10'))
}

stages {

    stage('Checkout') {

        steps {

            echo "Checkout Source"

            checkout scm

            sh 'git status'
        }
    }

    stage('Validate Project') {

        steps {

            echo "Validate Project Structure"

            sh '''
            dir
            '''

        }
    }

    stage('Install Dependencies') {

        steps {

            sh '''
            python --version
            pip install -r requirements.txt
            '''
        }
    }

    stage('Run Unit Tests') {

        steps {

            sh '''
            pytest tests
            '''
        }
    }

    stage('Build Docker Image') {

        steps {

            sh """
            docker build ^
              -t %IMAGE_NAME%:%IMAGE_TAG% ^
              .
            """
        }
    }

    stage('Deploy Databricks Notebooks') {

        steps {

            sh '''
            databricks workspace import-dir ^
              notebooks ^
              /EngineeringAI ^
              --overwrite
            '''
        }
    }

    stage('Trigger Databricks Pipeline') {

        steps {

            sh """
            databricks jobs run-now ^
                ${JOB_ID}
            """
        }
    }

    stage('Wait For Completion') {

        steps {

            echo "Waiting For Databricks Pipeline"

            sleep(
                time: 60,
                unit: 'SECONDS'
            )
        }
    }

    stage('Generate Reports') {

        steps {

            sh '''
            mkdir reports
            '''
        }
    }

    stage('Archive Reports') {

        steps {

            archiveArtifacts(
                artifacts: 'reports/**/*',
                fingerprint: true
            )
        }
    }
}

post {

    always {

        echo "Pipeline Completed"
    }

    success {

        echo "SUCCESS"
    }

    failure {

        echo "FAILED"
    }
}

}
